# build the switchlight build environment
FROM @IMAGE@
MAINTAINER @MAINTAINER@
COPY docker-init.sh /docker-init.sh
ENTRYPOINT ["/docker-init.sh"]
ENV TERM linux
ENV USER @USER@
ENV HOME @HOME@
CMD bash
