######################################################################
#
# GNUmakefile for the docker floodlight stuffs
#
######################################################################

top_srcdir			= ../../..

DOCKER_PROFILE			= onlbuilder7
DOCKER_OS			= opennetworklinux/builder7:1.1

include $(top_srcdir)/make/config.mk

-include docker.mk
-include $(top_srcdir)/make/docker-onlbuilder.mk
