# build the switchlight build environment
FROM @IMAGE@
MAINTAINER Carl Roth <carl.roth@bigswitch.com>
COPY apt.conf /etc/apt/apt.conf.d/98docker-host
COPY acng.conf /etc/apt-cacher-ng/acng.conf
COPY docker-init.sh /docker-init.sh
COPY sudoers /etc/sudoers.d/sudoers
RUN groupadd -o -g @GID@ @USER@
RUN useradd -o -u @UID@ -g @GID@ -M -d @HOME@ -s /bin/bash @USER@
ENTRYPOINT ["/docker-init.sh"]
ENV TERM linux
ENV USER @USER@
ENV HOME @HOME@
CMD bash
