######################################################################
#
# GNUmakefile for the docker floodlight stuffs
#
######################################################################

top_srcdir			= ../../..

DOCKER_PROFILE			= onlbuilder8
DOCKER_OS			= opennetworklinux/builder8:1.3

include $(top_srcdir)/make/config.mk

-include docker.mk
-include $(top_srcdir)/make/docker-onlbuilder.mk
