# build the switchlight build environment
FROM @IMAGE@
MAINTAINER Carl Roth <carl.roth@bigswitch.com>
COPY apt.conf /etc/apt/apt.conf.d/98docker-host
COPY acng.conf /etc/apt-cacher-ng/acng.conf
COPY docker-init.sh /docker-init.sh

# Jeff's switch light build is set up with a non-root user
USER root

# update the UID and GID for the local system
RUN usermod -o -u @UID@ -g @GID@ -d @HOME@ @USER@
RUN groupmod -o -g @GID@ @USER@

ENTRYPOINT ["/docker-init.sh"]
ENV TERM linux
ENV USER @USER@
ENV HOME @HOME@
CMD bash
